{{- range .Values.udpRoutes }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: {{ .name }}
  namespace: {{ include "oc-serve.namespace" $ }}
spec:
  parentRefs:
    - name: {{ .parentRef.name }}
      namespace: {{ .parentRef.namespace }}
      sectionName: {{ .parentRef.sectionName }}
  rules:
    - backendRefs:
        - name: {{ .backend.name }}
          namespace: {{ .backend.namespace }}
          port: {{ .backend.port }}
{{- end }}